# Generated by Django 3.0.8 on 2020-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=29, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('gender', models.CharField(max_length=500, null=True)),
                ('age', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
