# Generated by Django 3.0.8 on 2020-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0002_auto_20200723_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertuser',
            name='severity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='N', max_length=50, null=True),
        ),
    ]
