# Generated by Django 3.0.8 on 2020-07-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0003_alertuser_severity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertUser',
            new_name='AlertList',
        ),
    ]
