# Generated by Django 3.0.8 on 2020-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0004_auto_20200723_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geography', models.CharField(max_length=500, null=True)),
                ('severity', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='N', max_length=50, null=True)),
                ('population', models.BigIntegerField(null=True)),
                ('total_nodes', models.CharField(max_length=10, null=True)),
                ('live_nodes', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AlertList',
        ),
    ]
