# Generated by Django 3.0.8 on 2020-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0005_auto_20200728_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nodal_center',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
