# Generated by Django 3.0.8 on 2020-07-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0006_location_nodal_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='alert_status',
            field=models.CharField(choices=[('N', 'Not Sent'), ('Y', 'Sent')], default='N', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='nc_category',
            field=models.CharField(choices=[('P', 'Police'), ('A', 'Ambulance'), ('F', 'Fire Brigade')], default='A', max_length=50, null=True),
        ),
    ]
