# Generated by Django 3.0.8 on 2020-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0008_auto_20200801_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='live_nodes',
        ),
        migrations.RemoveField(
            model_name='location',
            name='total_nodes',
        ),
        migrations.AddField(
            model_name='city',
            name='live_nodes',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='total_nodes',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
