# Generated by Django 3.0.8 on 2020-08-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0010_location_disaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cctv',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
