# Generated by Django 3.0.8 on 2020-08-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0012_location_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='disaster_status',
            new_name='covid_status',
        ),
        migrations.AddField(
            model_name='location',
            name='fire_status',
            field=models.CharField(default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='flood_status',
            field=models.CharField(default=0, max_length=5, null=True),
        ),
    ]
